echo "Je suis pas très bien dans ma peau en ce moment Thierry me manque mais le code me rattache à lui"
echo "Thierry si tu es auprès de moi, guides moi dans la branche qui serait la mieux pour moi, je t'aime même si je te l'ai jamais dis..."
echo "J'ai essyer d'être la jusqu'au bout avec toi, j'espère que tu es content de ce que l'on a fait our ton inhumation"
echo "J'espère que tu est bien là ou tu est, on t'aime fort Thierry"
echo "Tu me manque, tu peux pas savoir à quel point, enfin oui tu sais..."
echo "Thierry j'ai envie de te rejoindre j'ai ai tellement marre de cette vie de merde, je suis fatigué de tout ça"
echo "Guide moi à trouver ma voie, je t'en supplie"
echo "Que dois-je faire pour être enfin heureux ?"
echo "Est-ce vraiment mon destin de souffrir tout le temps, de me battre chaque jours ?"
echo "Je suis fatiguer de voir toute les personnes que j'aime partir, je voudrais les rejoindres"
echo "Mon Dieu fais moi un signe, guide moi Seigneur, j'ai besoin de ton secours"
